In [73]:
import numpy as np
from scipy.stats import norm
import math
from scipy.optimize import minimize_scalar, minimize
from pathlib import Path
import time
from PIL import Image
import matplotlib.pyplot as plt

%config InlineBackend.figure_formats = 'svg'

In [74]:
class SimkinJNDModel:

    def __init__(self, L_MIN = 0.1, L_MAX = 300, screen_diag_inch = 16, screen_width_px = 1920, 
                screen_height_px = 1080, distance_m = 0.5, l_gray = 60):
        
        self.L_MIN = L_MIN
        self.L_MAX = L_MAX
        self.L0 = 1e-6

        diag_px = math.sqrt(screen_width_px ** 2 + screen_height_px ** 2)
        ppi = diag_px / screen_diag_inch
        
        pixel_size_m = 0.0254 / ppi # 1 дюйм = 0.0254 метра

        self.phi_screen = pixel_size_m / distance_m # считаем угловой размер пикселя на экране
        self.phi = self.phi_screen
        
        self.screen_width_px = screen_width_px
        self.screen_height_px = screen_height_px
        self.ppi = ppi
        self.l_gray = l_gray

    def _Simkin_A(self, La: float | np.ndarray) -> float | np.ndarray:
        a1: float = 4800000.0
        a2: float = 7100.0
        a3: float = 0.00045
        return 1.0 + np.sqrt(a1 * La) + a2 * La * (1.0 + np.sqrt(a3 * La))

    def _Simkin_l(self, La: float | np.ndarray) -> float | np.ndarray:
        L0: float = 0.000001
        return L0 * self._Simkin_A(La)

    def _Simkin_lambda(self, L: np.ndarray | float, La: float | np.ndarray) -> np.ndarray | float:
        Xao: float = 100.0
        return L / (Xao * self._Simkin_l(La))

    def _Simkin_LAt(self, lambda_: np.ndarray | float) -> np.ndarray | float:
        b1: float = 0.98
        b2: float = 0.1
        lambda1: float = 0.02
        lambda_arr = np.asarray(lambda_, dtype=np.float64)
        return np.where(lambda_arr <= 1.0, b1 * (lambda_arr + lambda1), lambda_arr ** (1.0 + b2))

    def _Simkin_ro(self, La: float | np.ndarray) -> float | np.ndarray:
        L1: float = 10.0
        L2: float = 0.000026
        c2: float = 0.25
        return (1.0 + L1 / (L2 + La)) ** c2

    def _Simkin_teta(self, phi: float, La: float | np.ndarray) -> float | np.ndarray:
        phi_omin: float = (1.0 / 60.0) * np.pi / 180.0
        return phi / (phi_omin * self._Simkin_ro(La))

    def _Simkin_S(self, teta: float) -> float:
        teta1: float = 6.1
        return (teta1 / teta + 1.0) ** 2

    def _simkin_nu(self, La: float | np.ndarray) -> float | np.ndarray:
        nu = 4.1 - 3.4 / (1.0 + np.exp(-0.5 - np.log10(La)))
        return np.clip(nu, 1.0, 4.0)

    def _simkin_T(self, t: float, La: float | np.ndarray) -> float | np.ndarray:
        return t / (0.05 * self._simkin_nu(La))

    def _simkin_C(self, T: float) -> float:
        return 1.0 + 1.0 / T

    def _Simkin_fN(self, La: float | np.ndarray, L: np.ndarray | float, LN: float) -> np.ndarray | float:
        sigma_N = 3.0 * LN / self._Simkin_l(La)
        lat_val = self._Simkin_LAt(self._Simkin_lambda(L, La))
        return np.sqrt(1.0 + (sigma_N * sigma_N) / (lat_val * lat_val))

    def _simkin_core(
        self,
        La: float | np.ndarray,
        L: np.ndarray | float,
        phi: float | None = None,
        LN: float = 0.0,
        t: float = 1
    ) -> np.ndarray | float:
        
        if phi is None:
            phi = self.phi

        return (
            self.L0
            * self._Simkin_A(La)
            * self._Simkin_LAt(self._Simkin_lambda(L, La))
            * self._Simkin_S(self._Simkin_teta(phi, La))
            * self._Simkin_fN(La, L, LN)
            * self._simkin_C(self._simkin_T(t, La))
        )
    
    def find_La_with_background(self, L_patch, optimizer = 'minimize_scalar', target_width_cm = None, mode = 'square'):
        '''
        L_patch подается в оригинальном разрешении
        
        '''

        n_total = self.screen_width_px * self.screen_height_px # общее количество пикселей на экране
        
        if (isinstance(L_patch, np.ndarray) and L_patch.size > 0 and L_patch.ndim == 2): # проверка на то, что L_patch это матрица
            h_patch_px, w_patch_px = L_patch.shape # размеры патча
            aspect_ratio = h_patch_px / w_patch_px # соотношение сторон патча

            if target_width_cm is None:
                target_w_px = w_patch_px
                target_h_px = h_patch_px
            else:
                target_w_px = int(np.round((target_width_cm / 2.54) * self.ppi)) # вычисление количества пикселей, которое будет
                target_h_px = int(np.round(target_w_px * aspect_ratio))          # занимать отмаштабированное изображение на экране

            n_patch_screen = min(target_w_px * target_h_px, n_total) # количество пикселей на экране, занимаемых отмаштабированным изображением

            scale = target_w_px / w_patch_px
            self.phi = scale * self.phi_screen
        else:
            n_patch_screen = 0
            self.phi = self.phi_screen
        
        n_bg = n_total - n_patch_screen # количество пикселей на экране, занимаемых фоном

        if L_patch.size > 0:
            logL = np.log(np.maximum(L_patch, 1e-12))
            log_La_min = float(min(logL.min(), math.log(self.l_gray)))
            log_La_max = float(max(logL.max(), math.log(self.l_gray)))
        else:
            log_La_min = -3.0
            log_La_max = 6.0

        den_patch = self._simkin_core(La=L_patch, L=L_patch)
        den_bg = self._simkin_core(La=self.l_gray, L=self.l_gray)

        def objective_log_La(log_La):
            curr_La = math.exp(float(log_La))
        
            if L_patch.size > 0:
                num_patch = self._simkin_core(La=curr_La, L=L_patch)
                if mode == 'abs':
                    sum_patch = (n_patch_screen / L_patch.size) * float(np.sum(np.abs(np.log(num_patch / den_patch)))) # версия с модулем
                elif mode == 'square':
                    sum_patch = (n_patch_screen / L_patch.size) * float(np.sum((np.log(num_patch / den_patch))**2)) # версия с квадратом
            else:
                sum_patch = 0.0
            
            num_bg = self._simkin_core(La=curr_La, L=self.l_gray)
            if mode == 'abs':
                sum_bg = n_bg * np.abs(math.log(num_bg / den_bg)) # версия с модулем
            elif mode == 'square':
                sum_bg = n_bg * (math.log(num_bg / den_bg))**2 # версия с квадратом
            
            return float((sum_patch + sum_bg) / n_total)

        if optimizer == 'minimize_scalar':

            history_x = []
            history_loss = []

            def tracked_objective(log_la):
                loss = objective_log_La(log_la)
                history_x.append(float(log_la))
                history_loss.append(float(loss))
                return loss

            result = minimize_scalar(
                tracked_objective,
                bounds=(log_La_min, log_La_max),
                method='bounded',
                options={'xatol': 1e-6},
            )

            self.La = math.exp(float(result.x))

        elif optimizer == 'log_grid_search':

            log_space = np.linspace(log_La_min, log_La_max, num=1000)

            best_la = 0
            min_loss = 1e10

            for log_la in log_space:
                loss = objective_log_La(log_la)
                if min_loss > loss:
                    min_loss = loss
                    best_la = np.exp(log_la)

            self.La = best_la

        if optimizer == 'L-BFGS-B':
            
            if L_patch.size > 0:
                mean_L = (float(np.mean(L_patch)) * n_patch_screen + self.l_gray * n_bg) / n_total
            else:
                mean_L = self.l_gray
                
            mean_log = math.log(max(mean_L, 1e-12))
            
            def wrapped_objective(x):
                return objective_log_La(x.item())
            
            result = minimize(
                fun=wrapped_objective,
                x0=np.array([mean_log]),
                bounds=[(log_La_min, log_La_max)],
                method='L-BFGS-B',
                options={'ftol': 1e-9}
            )
            
            self.La = math.exp(float(result.x[0]))
        
        return self.La

    def build_level_boundaries(self):
        L_right_bounds = []
        L_curr = self.La
        while L_curr < self.L_MAX:
            L_curr += self._simkin_core(L = L_curr, La = self.La)
            L_right_bounds.append(min(L_curr, self.L_MAX))

        L_left_bounds = []
        L_curr = self.La
        while L_curr > self.L0:
            L_curr -= self._simkin_core(L = L_curr, La = self.La)
            L_left_bounds.append(max(L_curr, self.L0))

        self.len_left = len(L_left_bounds)

        L_left_bounds.reverse()

        self.bounds = np.array(L_left_bounds + [self.La] + L_right_bounds)

        return self.bounds

    def L_to_k(self, L): # всегда берем нижнюю границу интервала, в который попали
        idx = np.searchsorted(self.bounds, L, side='right') - 1
        idx = np.clip(idx, 0, len(self.bounds) - 1)
        return idx - self.len_left
        
    def k_to_L(self, k): # всегда берем нижнюю границу интервала, в который попали
        return self.bounds[k + self.len_left]

In [75]:
class ImageConverter:
    def __init__(self, L_MIN: float = 0.1, L_MAX: float = 300):

        self.M = np.array([
            [0.4124564,  0.3575761,  0.1804375],
            [0.2126729,  0.7151522,  0.0721750],
            [0.0193339,  0.1191920,  0.9503041]
        ])
        self.M_inv = np.array([
            [ 3.1338561, -1.6168667, -0.4906146],
            [-0.9787684,  1.9161415,  0.0334540],
            [ 0.0719453, -0.2289914,  1.4052427]
        ])

        self.L_MAX = L_MAX
        self.L_MIN = L_MIN
        self.coord_white = np.array([0.3127, 0.3290, 0.3583])
        self.eps = 1e-10

    def sRGB_Companding(self, linear_image: np.ndarray) -> np.ndarray:
        linear = np.clip(np.asarray(linear_image, dtype=np.float64), 0.0, 1.0)
        
        encoded = np.where(
            linear <= 0.0031308,
            linear * 12.92,
            1.055 * (linear ** (1.0 / 2.4)) - 0.055
        )
        return encoded

    def Inverse_sRGB_Companding(self, image: np.ndarray) -> np.ndarray:
        img = np.asarray(image, dtype=np.float64)
        
        linear = np.where(
            img <= 0.04045,
            img / 12.92,
            ((img + 0.055) / 1.055) ** 2.4
        )
        return linear

    def Linear_RGB_to_XYZ(self, image: np.ndarray) -> np.ndarray:
        XYZ_image = image.reshape(-1, 3)
        return (XYZ_image @ self.M.T).reshape(image.shape)

    def XYZ_to_xyzL(self, XYZ_image: np.ndarray) -> np.ndarray:
        """
        Возвращает тензор (H, W, С), С = 4 (x, y, z, L)
        """
        sum_xyz = XYZ_image.sum(keepdims=True, axis=-1)

        xyz = XYZ_image / (sum_xyz + self.eps)
        
        is_black = (sum_xyz < self.eps).squeeze(-1) 

        if np.any(is_black):
            xyz[is_black] = self.coord_white

        Y = XYZ_image[..., 1]

        L_norm = np.clip(Y, 0.0, 1.0)

        L_physical = self.L_MIN + L_norm * (self.L_MAX - self.L_MIN)

        L_physical = np.expand_dims(L_physical, axis=-1)

        xyzL = np.concatenate([xyz, L_physical], axis=-1) # (H, W, С) С = 4 (x, y, z, L)

        return xyzL

    def RGB_to_xyzL(self, image: np.ndarray) -> np.ndarray:
        """
        На вход изображение - ненормализованный тензор RGB
        Возвращается тензор (x, y, z, L). L - физическая яркость на основе параметров монитора, в диапазоне (L_MIN, L_MAX)
        """
    
        # [0, 1]
        norm_img = np.asarray(image, dtype=np.float64) / 255.0
    
        # sRGB -> linRGB
        linRGBimg = self.Inverse_sRGB_Companding(norm_img)
    
        #linRGB -> XYZ
        XYZ_image = self.Linear_RGB_to_XYZ(linRGBimg)
    
        xyzL_image = self.XYZ_to_xyzL(XYZ_image)

        return xyzL_image

    def L_to_gray(self, L: np.ndarray | float) -> np.ndarray | np.uint8:
        """
        На вход L - число или матрица ненормированных яркостей
        Возвращается матрица или число (np.uint8) со значениями в градациях серого (от 0 до 255)
        """

        Y_lin = (L - self.L_MIN) / (self.L_MAX - self.L_MIN)

        Y_lin = np.clip(Y_lin, 0.0, 1.0)

        V = self.sRGB_Companding(Y_lin)

        gray_matrix = np.rint(V * 255).astype(np.uint8)

        return gray_matrix

In [76]:
jnd_model = SimkinJNDModel()
converter = ImageConverter()

In [77]:
from itertools import product
import pandas as pd

img_path = Path('../examples/bright.jpg')

image = Image.open(img_path)

np_image = np.array(image)

xyzL = converter.RGB_to_xyzL(np_image)

L_patch = xyzL[..., -1]

bright = []

for l_gray, mode, target_width_cm in product([30, 60, 90], ['abs', 'square'], [None, 2, 4, 8, 16]):

    jnd_model.l_gray = l_gray

    jnd_model.find_La_with_background(L_patch, target_width_cm=target_width_cm, mode=mode)

    jnd_model.build_level_boundaries()

    print(f'Средняя яркость патча: {L_patch.mean()}, яркость фона: {jnd_model.l_gray}, mode: {mode}'
        f'\nНайденная La: {jnd_model.La}, размер патча: {target_width_cm} cm')

    print(f'Кол-во уровней: {len(jnd_model.bounds)}\nУровни:\n {jnd_model.bounds[:4]}...{jnd_model.bounds[-4:]}')

    bright.append({
        'Средняя яркость патча': L_patch.mean(),
        'Яркость фона': l_gray,
        'optimize mode': mode,
        'La': jnd_model.La,
        'Размер патча, см': target_width_cm,
        'Кол-во уровней': len(jnd_model.bounds)
    })

    print('-'*120)

Средняя яркость патча: 100.3806046678135, яркость фона: 30, mode: abs
Найденная La: 30.000005881817785, размер патча: None cm
Кол-во уровней: 17
Уровни:
 [1.00000000e-06 5.03745412e-02 4.07227569e-01 9.95668615e-01]...[125.90082189 185.33934713 276.28898945 300.        ]
------------------------------------------------------------------------------------------------------------------------
Средняя яркость патча: 100.3806046678135, яркость фона: 30, mode: abs
Найденная La: 30.0000040679937, размер патча: 2 cm
Кол-во уровней: 3
Уровни:
 [1.00000000e-06 3.00000041e+01 3.00000000e+02]...[1.00000000e-06 3.00000041e+01 3.00000000e+02]
------------------------------------------------------------------------------------------------------------------------
Средняя яркость патча: 100.3806046678135, яркость фона: 30, mode: abs
Найденная La: 30.00000501571352, размер патча: 4 cm
Кол-во уровней: 4
Уровни:
 [1.00000000e-06 3.00000050e+01 1.11384297e+02 3.00000000e+02]...[1.00000000e-06 3.00000050e+0

In [78]:
img_path = Path('../examples/dark.jpg')

image = Image.open(img_path)

np_image = np.array(image)

xyzL = converter.RGB_to_xyzL(np_image)

L_patch = xyzL[..., -1]

dark = []

for l_gray, mode, target_width_cm in product([30, 60, 90], ['abs', 'square'], [None, 2, 4, 8, 16]):

    jnd_model.l_gray = l_gray

    jnd_model.find_La_with_background(L_patch, target_width_cm=target_width_cm, mode=mode)

    jnd_model.build_level_boundaries()

    print(f'Средняя яркость патча: {L_patch.mean()}, яркость фона: {jnd_model.l_gray}, mode: {mode}'
        f'\nНайденная La: {jnd_model.La}, размер патча: {target_width_cm} cm')

    print(f'Кол-во уровней: {len(jnd_model.bounds)}\nУровни:\n {jnd_model.bounds[:4]}...{jnd_model.bounds[-4:]}')

    dark.append({
        'Средняя яркость патча': L_patch.mean(),
        'Яркость фона': l_gray,
        'optimize mode': mode,
        'La': jnd_model.La,
        'Размер патча, см': target_width_cm,
        'Кол-во уровней': len(jnd_model.bounds)
    })

    print('-'*120)

Средняя яркость патча: 9.155382841856174, яркость фона: 30, mode: abs
Найденная La: 86.51840613622278, размер патча: None cm
Кол-во уровней: 14
Уровни:
 [1.00000000e-06 8.41216852e-01 2.18421341e+00 4.29375356e+00]...[119.0344574  165.22131388 231.46601074 300.        ]
------------------------------------------------------------------------------------------------------------------------
Средняя яркость патча: 9.155382841856174, яркость фона: 30, mode: abs
Найденная La: 30.00000060603427, размер патча: 2 cm
Кол-во уровней: 3
Уровни:
 [1.00000000e-06 3.00000006e+01 3.00000000e+02]...[1.00000000e-06 3.00000006e+01 3.00000000e+02]
------------------------------------------------------------------------------------------------------------------------
Средняя яркость патча: 9.155382841856174, яркость фона: 30, mode: abs
Найденная La: 30.000002810824693, размер патча: 4 cm
Кол-во уровней: 4
Уровни:
 [1.00000000e-06 3.00000028e+01 1.40726039e+02 3.00000000e+02]...[1.00000000e-06 3.00000028e+

In [79]:
df_bright = pd.DataFrame(bright)
df_dark = pd.DataFrame(dark)

df_bright.to_csv('results/bright.csv')
df_dark.to_csv('results/dark.csv')

In [80]:
display(df_bright)

,Средняя яркость патча,Яркость фона,optimize mode,La,"Размер патча, см",Кол-во уровней
0,100.380605,30,abs,30.000006,NaN,17
1,100.380605,30,abs,30.000004,2.0,3
2,100.380605,30,abs,30.000005,4.0,4
3,100.380605,30,abs,30.000001,8.0,9
4,100.380605,30,abs,29.999996,16.0,27
5,100.380605,30,square,41.238685,NaN,16
6,100.380605,30,square,30.073781,2.0,3
7,100.380605,30,square,30.301616,4.0,4
8,100.380605,30,square,31.270507,8.0,9
9,100.380605,30,square,186.257812,16.0,22


In [81]:
display(df_dark)

,Средняя яркость патча,Яркость фона,optimize mode,La,"Размер патча, см",Кол-во уровней
0,9.155383,30,abs,86.518406,NaN,14
1,9.155383,30,abs,30.000001,2.0,3
2,9.155383,30,abs,30.000003,4.0,4
3,9.155383,30,abs,30.000000,8.0,6
4,9.155383,30,abs,83.384262,16.0,19
5,9.155383,30,square,83.581179,NaN,14
6,9.155383,30,square,30.880308,2.0,3
7,9.155383,30,square,115.131627,4.0,3
8,9.155383,30,square,93.045848,8.0,5
9,9.155383,30,square,80.336962,16.0,19
